# Virtual KITTI recipe referencing configs/base.yaml
defaults:
  - base

data:
  dataset_type: virtual_kitti
  data_root:
    default:
      - /data/virtual_kitti_focal_stacks
      - "D:/Files/paper/DepthEstimation/Dataset/VirtualKITTI/vkitti_2.0.3_rgb"
    all_in_focus:
      - /data/virtual_kitti_focal_stacks
      - "D:/Files/paper/DepthEstimation/Dataset/VirtualKITTI/vkitti_2.0.3_rgb"
    depth:
      - /data/virtual_kitti_focal_stacks
      - "D:/Files/paper/DepthEstimation/Dataset/VirtualKITTI/vkitti_2.0.3_depth"
  train_filelist: data/filelists/vkitti_train.txt
  val_filelist: data/filelists/vkitti_val.txt
  test_filelist: data/filelists/vkitti_test.txt
  focal_stack_size: 7
  focal_range: [0.5, 80.0]

output:
  save_dir: outputs/experiments/virtual_kitti

training:
  batch_size: 1
  gradient_accumulation_steps: 2
